# Please DO NOT use TAB key. Instead, use 2 spaces to indent.

plugin:
  # You can set it to:
  # INFO = ONLY all major errors, crashes, etc.
  # PRODUCTION = All the Major Warnings, Errors and Crashes
  # FINE = Warnings, Errors, Crashes
  # DEBUG = EVERYTHING + EXTRA Verbose OUTPUT
  logging-mode: "PRODUCTION"
  
discord:
  # You can add as many webhook urls as you'd like.
  # The Format is webhook-name: "full-webhook-url"
  #                    COPY AND PASTE FROM DISCORD
  # You can have a global or default webhook by naming it the same.
  webhooks:
    nothing: "https://nothing.net/"
    # ETC...

  messages:
    # You can add as many different custom messages as you want.
    # The Format is message-name: "message-file-name"
    # The message files should go into messages/ folder.
    example1: "example"
